name: Test Workflow für Cihat
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: NAME="Stephan"
    steps:
      - name: Git clone
        run: |
          ls -la
          git clone ${{secrets.REPO_URL}}
          echo ${{env.NAME}}
          ls -la
