name: Test Workflow für Cihat
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        run: |
          ls -la
          git clone https://github.com/StephanLoecher/Github_Cihat.git
          ls -la
